In [1]:
import os
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
import random
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import zipfile

In [2]:
# Specify the path to your zip file
zip_file_path = 'C:\\Users\\Aditya Kudva\\Downloads\\kagglecatsanddogs_3367a.zip'
# Specify the directory where you want to extract its contents
extract_to_path = 'C:\\Users\\Aditya Kudva\\Downloads\\Extracted'

# Create the directory if it doesn't exist
os.makedirs(extract_to_path, exist_ok=True)

# Extract the zip file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to_path)

print("Extraction Complete")

Extraction Complete


In [3]:
# Base directory where the extracted files are located
base_dir = 'C:\\Users\\Aditya Kudva\\Downloads\\Extracted\\PetImages'

categories = ['Cat', 'Dog']

data = []  # This will hold tuples of (image_data, label)

for category in categories:
    path = os.path.join(base_dir, category)
    label = categories.index(category)

    if os.path.exists(path):
        for img in os.listdir(path):
            img_path = os.path.join(path, img)
            try:
                pet_img = cv.imread(img_path, cv.IMREAD_GRAYSCALE)
                if pet_img is not None:
                    pet_img = cv.resize(pet_img, (64, 64))  # Resize to (64, 64)
                    data.append((pet_img.flatten(), label))  # Append a tuple
            except Exception as e:
                print(f"Error loading image {img_path}: {e}")
    else:
        print(f"Directory not found: {path}")

print("Data loading complete.")

Data loading complete.


In [4]:
random.shuffle(data)

features = []
labels = []

for feature, label in data:
    features.append(feature)
    labels.append(label)  

In [5]:
x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)
x_train, x_test, y_train, y_test

([array([154, 152, 143, ..., 134, 159, 140], dtype=uint8),
  array([ 63,  81,  92, ..., 118, 114, 110], dtype=uint8),
  array([232, 228, 240, ..., 186, 119, 200], dtype=uint8),
  array([144, 144, 144, ..., 144, 143, 144], dtype=uint8),
  array([ 99,  99, 103, ..., 112, 112, 108], dtype=uint8),
  array([220, 221, 219, ..., 209, 215, 230], dtype=uint8),
  array([218, 233, 231, ..., 198, 196, 196], dtype=uint8),
  array([ 86,  96, 104, ...,  87,  83,  76], dtype=uint8),
  array([170, 170, 173, ..., 239, 242, 243], dtype=uint8),
  array([255, 254, 255, ..., 136, 146, 151], dtype=uint8),
  array([  9,   9,  13, ..., 182, 182, 182], dtype=uint8),
  array([209, 206, 209, ..., 237, 221, 233], dtype=uint8),
  array([ 14,  14,  21, ..., 114,  46,  52], dtype=uint8),
  array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
  array([ 24,  34,  30, ..., 123, 121, 120], dtype=uint8),
  array([167, 168, 168, ..., 150, 148, 144], dtype=uint8),
  array([180, 166, 196, ..., 178, 208, 192], dtype=uint8

In [7]:
model = SVC()
model



SVC()

In [ ]:
model.fit(x_train, y_train)
accuracy = model.score(x_test, y_test)
print(f"Test accuracy: {accuracy * 100:.2f}%")

In [ ]:
mypet = x_test[2].reshape(100,100)
prediction = model.predict(x_test)
accuracy = model.score(x_test,y_test)
print('Accuracy :', accuracy)
print('Prediction is', categories[prediction[2]])
plt.imshow(mypet, cmap ='gray')
plt.show()

In [ ]:
model = SVC(C=1, kernel='poly', gamma='auto')
model